
# NOTE: keep in sync with .gitignore
# (except for dotfiles which are automatically excluded)
exclude:
  - node_modules
  - bin
  - src
  - vendor # rubygems in TravisCI
  - Gemfile
  - Gemfile.lock
  - package.json
  - package-lock.json
  - webpack.config.js
  - gulpfile.js
  - README.md

plugins:
  - jekyll-paginate
  - jekyll-archives

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

production_baseurl: https://fullcalendar.io

fullcalendar_org: https://github.com/fullcalendar
fullcalendar_repo: https://github.com/fullcalendar/fullcalendar
fullcalendar_scheduler_repo: https://github.com/fullcalendar/fullcalendar-scheduler
fullcalendar_react_repo: https://github.com/fullcalendar/fullcalendar-react
fullcalendar_vue_repo: https://github.com/fullcalendar/fullcalendar-vue
fullcalendar_angular_repo: https://github.com/fullcalendar/fullcalendar-angular

fullcalendar_react_playground: https://codesandbox.io/s/2z6wp2jozn
fullcalendar_vue_playground: https://codesandbox.io/s/8xyz32l0r8
fullcalendar_angular_playground: https://stackblitz.com/github/fullcalendar/fullcalendar-example-projects/tree/master/angular

disqus_shortname: adamshawsblog

paginate: 10
paginate_path: /blog/page:num

# ordered by how they should appear in UI
available_versions:

  - id: v4
    collection: docs-v4
    is_latest: true

  - id: v3
    collection: docs-v3

  - id: v2
    aliased_to: v3

  - id: v1
    collection: docs-v1

# `output: true` says a page should be generated for each document.
# NOTE: if you change the permalink structure, you must also change
# the permalinks in the _docs-*/index.md files.
collections:

  docs-v4:
    output: true
    permalink: /docs/:slug

  docs-v3:
    output: true
    permalink: /docs/v3/:slug

  docs-v1:
    output: true
    permalink: /docs/v1/:slug

  posts: # will output by default
    permalink: /blog/:year/:month/:title

defaults:
  # will apply default values to all posts
  - scope:
      path: ""
      type: posts
    values:
      layout: blog-post
